kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.15
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go build

- name: test
  image: golang:1.15
  volumes:
  - name: deps
    path: /go
  environment:
    DB_HOST: mysql
    DB_USERNAME: tiwengo
    DB_PASSWORD: password
    DB_NAME: tiwengo
    REDIS_HOST: redis
  commands:
  - go test -v

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

volumes:
- name: deps
  temp: {}

services:
- name: redis
  image: redis:6-alpine
- name: mysql
  image: mysql:8
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: tiwengo
    MYSQL_USER: tiwengo
    MYSQL_PASSWORD: password

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy-staging

steps:
- name: release
  image: plugins/docker
  settings:
    repo: tccgov.azurecr.io/tiwengo
    tags:
    - ${DOCKER_TAG}
    registry: tccgov.azurecr.io
    username: tccgov
    password: 
      from_secret: docker_password

- name: deploy
  image: appleboy/drone-ssh
  volumes:
  - name: ssh_key
    path: /root/.ssh
  settings:
    host: 10.78.0.1
    username: ar0660
    key_path: /root/.ssh/id_rsa
    script:
    - cd /home/ar0660/workspace
    - sudo docker-compose down
    - sudo docker-compose up -d

volumes:
- name: ssh_key
  host:
    path: /home/ar0660/.ssh

trigger:
  event:
  - promote
  target:
  - staging

---
kind: pipeline
type: kubernetes
name: deploy-production

steps:
- name: release
  image: plugins/docker
  settings:
    repo: tccgov.azurecr.io/tiwengo
    tags:
    - ${DOCKER_TAG}
    registry: tccgov.azurecr.io
    username: tccgov
    password: 
      from_secret: docker_password

- name: deploy
  image: appleboy/drone-ssh
  volumes:
  - name: ssh_key
    path: /root/.ssh
  settings:
    host: proxy.tccg.tw
    username: ar0660
    key_path: /root/.ssh/id_rsa
    script:
    - echo "--- TODO ---"
    - echo "kubectl apply -f deployment.yaml"
    - echo "--- OR ---"
    - echo "helm upgrade tiwengo ar0660/tiwengo -f values.yaml -n default"
    - echo "--- END ---"

volumes:
- name: ssh_key
  host:
    path: /home/ar0660/.ssh

trigger:
  event:
  - promote
  target:
  - production
