kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:1.15
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go build

- name: test
  image: golang:1.15
  volumes:
  - name: deps
    path: /go
  environment:
    DB_HOST: mysql
    DB_USERNAME: tiwengo
    DB_PASSWORD: password
    DB_NAME: tiwengo
    REDIS_HOST: redis
  commands:
  - go test -v

volumes:
- name: deps
  temp: {}

services:
- name: redis
  image: redis:6-alpine
- name: mysql
  image: mysql:8
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: tiwengo
    MYSQL_USER: tiwengo
    MYSQL_PASSWORD: password

---
kind: pipeline
type: docker
name: deploy

steps:
- name: release
  image: plugins/docker
  settings:
    repo: tccgov.azurecr.io/tiwengo
    tags:
    - $DOCKER_TAG
    registry: tccgov.azurecr.io
    username: tccgov
    password: 
      from_secret: docker_password

trigger:
  event:
  - promote
  target:
  - production
